"""update comment model

Revision ID: 2c000f18e3d4
Revises: 821243dcddee
Create Date: 2023-11-19 19:10:02.819375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c000f18e3d4'
down_revision: Union[str, None] = '821243dcddee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('photo_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('update_status', sa.Boolean(), nullable=True))
    op.drop_constraint('comments_image_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'images', ['photo_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_image_id_fkey', 'comments', 'images', ['image_id'], ['id'])
    op.drop_column('comments', 'update_status')
    op.drop_column('comments', 'photo_id')
    # ### end Alembic commands ###
