"""update image and qr model

Revision ID: 4342f9c6cdd3
Revises: a3e9f4225c4f
Create Date: 2023-11-20 01:53:13.263628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4342f9c6cdd3'
down_revision: Union[str, None] = 'a3e9f4225c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Qr_codes', sa.Column('images_id', sa.Integer(), nullable=True))
    op.drop_constraint('Qr_codes_photo_id_fkey', 'Qr_codes', type_='foreignkey')
    op.create_foreign_key(None, 'Qr_codes', 'images', ['images_id'], ['id'])
    op.drop_column('Qr_codes', 'photo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Qr_codes', sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Qr_codes', type_='foreignkey')
    op.create_foreign_key('Qr_codes_photo_id_fkey', 'Qr_codes', 'images', ['photo_id'], ['id'])
    op.drop_column('Qr_codes', 'images_id')
    # ### end Alembic commands ###
