"""some change model

Revision ID: 4430269f16ae
Revises: 3728e3636b58
Create Date: 2023-11-20 13:44:03.315156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4430269f16ae'
down_revision: Union[str, None] = '3728e3636b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Qr_codes', sa.Column('image_id', sa.Integer(), nullable=True))
    op.drop_constraint('Qr_codes_photo_id_fkey', 'Qr_codes', type_='foreignkey')
    op.create_foreign_key(None, 'Qr_codes', 'images', ['image_id'], ['id'])
    op.drop_column('Qr_codes', 'photo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Qr_codes', sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Qr_codes', type_='foreignkey')
    op.create_foreign_key('Qr_codes_photo_id_fkey', 'Qr_codes', 'images', ['photo_id'], ['id'])
    op.drop_column('Qr_codes', 'image_id')
    # ### end Alembic commands ###
