"""update comment model_1

Revision ID: c3876fc5b6d7
Revises: 2c000f18e3d4
Create Date: 2023-11-19 21:24:14.464169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3876fc5b6d7'
down_revision: Union[str, None] = '2c000f18e3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('image_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_photo_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'photo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_photo_id_fkey', 'comments', 'images', ['photo_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'image_id')
    # ### end Alembic commands ###
